run_name: #name of the run
  "small-example"
bwa_ref: #full path to bwa_reference_index
  "~/tools/bwa_hg19_index/hg19.fa"
calib_params: #Calib cluster parameters
  "-e 1 -k 5 -m 6 -l1 3 -l2 3 -t 2 -c 4 --no-sort --silent"
smrttools_full_path: #SMRTtools bin path for Pacbio based analysis
  "/groups/lackgrp/projects/inv-longread-snpstarrseq/code/smrtlink/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/pacbio/unanimity/binwrap/ccs"
parts: #Pacbio based analysis number of parts
  10
longread_adaptor:
  "/groups/lackgrp/projects/inv-longread-snpstarrseq/analysis/ccs-mapping/tidy-analysis/adaptor-sequence.fa"
snp_annotation: #SNP annotation file path (See misc section)
  "/groups/lackgrp/projects/dev-snpstarrseq-pipeline/analysis/publication-figures/dbsnp150.hg19.chr6.snp.gz"
bi_allelic_NBR_mincount:
  5
capture_bed: #full path to capture bed file.
  "/groups/lackgrp/projects/inv-mattfreedman-snpstarrseq/analysis/process-asymmetric/snp-genotyping/mutation/total500.bed"

longread_validation: #System path to Pacbio (CCS) long read alingment file. (must be same reference genome)
  "/groups/lackgrp/projects/dev-snpstarrseq-pipeline/raw-data/small-realdata/longread.bam"

fragment_retreival: #Contains input file information for for enhancer reconstruction from asymmetric reads (Illumina) or Pacbio. NOTE: One of these methods can be used in one run.
  # asym: #"Asym" for asymmetric reads. This mode requires longshort and shortlong fields to be filled.
  #   longshort:
  #     r1:
  #       - "raw-data/small-realdata/sample.longshort.r1.fastq.gz"
  #     r2:
  #       - "raw-data/small-realdata/sample.longshort.r2.fastq.gz"
  #   shortlong:
  #     r1:
  #       - "raw-data/small-realdata/sample.shortlong.r1.fastq.gz"
  #     r2:
  #       - "raw-data/small-realdata/sample.shortlong.r2.fastq.gz"
  pb: #"pb" for Pacbio is the preferred way for enhancer fragment retreival.
      reads: 
        "/groups/lackgrp/projects/inv-longread-snpstarrseq/raw-data/data2/pb/r64044_20201212_021108/3_C01/m64044_201214_151520.subreads.bam"


quantification: #Contains the input information for mRNA quantification samples.
  lib: #lib could be used for library sample.
    r1:
      - "raw-data/small-realdata/sample.lib.r1.fastq.gz"
    r2:
      - "raw-data/small-realdata/sample.lib.r2.fastq.gz"
  "481": #Other samples can be named as follows.
    r1:
      - "raw-data/small-realdata/sample.481.r1.fastq.gz"
    r2:
      - "raw-data/small-realdata/sample.481.r2.fastq.gz"  
  "482":
    r1:
      - "raw-data/small-realdata/sample.481.r1.fastq.gz"
    r2:
      - "raw-data/small-realdata/sample.481.r2.fastq.gz"  
  "483":
      r1:
        - "raw-data/small-realdata/sample.481.r1.fastq.gz"
      r2:
        - "raw-data/small-realdata/sample.481.r2.fastq.gz"  

bi_allelic_comparisons: #contains the design information for the comparisons.
  "comp_a": # comparison name 
    dna : "lib" # dna Input name (for standalone usage)
    mrna :  # same names used in the quantificaiton section.
      - "481"
      - "482"
      - "483"
  "comp_b": # there is no limited for number of comparsions could be made
    dna : "lib"
    mrna : 
      - "481"
      - "482"
      - "483"

