dna_samples:
  longshort:
    r1:
      - "raw-data/simulated-data/longshort.r1.fastq.gz"
    r2:
      - "raw-data/simulated-data/longshort.r2.fastq.gz"
  shortlong:
    r1:
      - "raw-data/simulated-data/shortlong.r1.fastq.gz"
    r2:
      - "raw-data/simulated-data/shortlong.r2.fastq.gz"

capture_bed:
  "/groups/lackgrp/projects/dev-snpstarrseq-pipeline/raw-data/simulated-data/target.bed"

        
mrna_samples:
  lib:
    r1:
      - "sample.lib.r1.fastq.gz"
    r2:
      - "sample.lib.r2.fastq.gz"
  "481":
    r1:
      - "sample.481.r1.fastq.gz"
    r2:
      - "sample.481.r2.fastq.gz"  
