run_name: #name of the run --> This field is mandatory
  "small-example2"
bwa_ref: #full path to bwa_reference_index --> This field is mandatory
  "~/tools/bwa_hg19_index/hg19.fa"
calib_params: #Calib cluster parameters --> This field is mandatory if asymmetric method is used for enhancer fragment retrival
  "-e 1 -k 5 -m 6 -l1 3 -l2 3 -t 2 -c 4 --no-sort --silent"
snp_annotation: #SNP annotation file path (See misc section) --> This field is optional. To skip annotation, simply remove from config or set it to "noannot".
  "raw-data/small-realdata/dbsnp150.hg19.chr6.snp.gz"
bi_allelic_NBR_mincount: # This field is mandatory.
  5
capture_bed: # full path to capture bed file. --> This field is mandatory 
  "raw-data/small-realdata/capture.bed"

longread_validation: # System path to Pacbio (CCS) long read alingment file. (must be same reference genome) --> This field is optional
  "raw-data/small-realdata/longread.bam"

fragment_retreival: # Contains input file information for for enhancer reconstruction from asymmetric reads (Illumina) or Pacbio. NOTE: One of these methods can be used in one run. --> This field is mandatory
  asym: #"Asym" for asymmetric reads. This mode requires longshort and shortlong fields to be filled.
    longshort:
      r1:
        - "raw-data/small-realdata/sample.longshort.r1.fastq.gz"
      r2:
        - "raw-data/small-realdata/sample.longshort.r2.fastq.gz"
    shortlong:
      r1:
        - "raw-data/small-realdata/sample.shortlong.r1.fastq.gz"
      r2:
        - "raw-data/small-realdata/sample.shortlong.r2.fastq.gz"
  # pb: #"pb" for Pacbio is the preferred way for enhancer fragment retreival.
  #     reads: 
  #       "/groups/lackgrp/projects/inv-longread-snpstarrseq/raw-data/data2/pb/r64044_20201212_021108/3_C01/m64044_201214_151520.subreads.bam"

quantification: #Contains the input information for mRNA quantification samples. --> This field is mandatory
  lib: #lib could be used for library sample.
    r1:
      - "raw-data/small-realdata/sample.lib.r1.fastq.gz"
    r2:
      - "raw-data/small-realdata/sample.lib.r2.fastq.gz"
  "481": #Other samples can be named as follows.
    r1:
      - "raw-data/small-realdata/sample.481.r1.fastq.gz"
    r2:
      - "raw-data/small-realdata/sample.481.r2.fastq.gz"  
  "482":
    r1:
      - "raw-data/small-realdata/sample.481.r1.fastq.gz"
    r2:
      - "raw-data/small-realdata/sample.481.r2.fastq.gz"  
  "483":
      r1:
        - "raw-data/small-realdata/sample.481.r1.fastq.gz"
      r2:
        - "raw-data/small-realdata/sample.481.r2.fastq.gz"  

bi_allelic_comparisons: #contains the design information for the comparisons. --> This field is mandatory
  "comp_a": # comparison name 
    dna : "lib" # dna Input name (for standalone usage)
    mrna :  # same names used in the quantificaiton section.
      - "481"
      - "482"
      - "483"
  "comp_b": # there is no limited for number of comparsions could be made
    dna : "lib"
    mrna : 
      - "481"
      - "482"
      - "483"


### following settings are for Pacbio based analysis.
smrttools_full_path: #SMRTtools bin path for Pacbio based analysis --> This field is mandatory if pacbio method is used for enhancer fragment retrival
  "/groups/lackgrp/projects/inv-longread-snpstarrseq/code/smrtlink/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/pacbio/unanimity/binwrap/ccs"
parts: #Pacbio based analysis number of parts --> This field is mandatory if pacbio method is used for enhancer fragment retrival
  10
longread_adaptor: # Contains the sequences of adapters flanking the enhancer fragment --> This field is mandatory if pacbio method is used for enhancer fragment retrival
  "raw-data/small-realdata/pacbio-longread-adaptor.fa"